version: "3.4"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bookerdewitt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:8.5.9-alpine
    container_name: booker-dewitt_flyway
    command: -url=jdbc:postgresql://db/bookerdewitt -schemas=public -user=admin
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
volumes:
  db:
    name: booker-dewitt_postgres